[package]
name = "confirm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
promkit = { path = "../../promkit", features = ["confirm"] }

[[bin]]
name = "confirm"
path = "src/confirm.rs"
