[package]
name = "promkit"
version = "0.8.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2021"
description = "A toolkit for building your own interactive command-line tools"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[lib]
name = "promkit"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.95"
promkit-core = { path = "../promkit-core", version = "=0.1.0" }
promkit-widgets = { path = "../promkit-widgets", version = "=0.1.0" }
radix_trie = { workspace = true }
